SELECT COURSES.NAME AS COURSE, STUDENTS.FIRST_NAME, STUDENTS.LAST_NAME
FROM COURSES
JOIN GROUPS ON COURSES.COURSE_ID = GROUPS.COURSE_ID
JOIN STUDENTS ON GROUPS.GROUP_ID = STUDENTS.GROUP_ID
ORDER BY COURSE ASC